### ISSUE TITLE
Can not import blspy

### ISSUE THREAD

**Issue by dkaparis** [pshenmic/electrum-dash#14]
I'm trying the current AppImage release 4.1.7.4 on an Arch Linux machine.

The application fails to start with the following output:

```
Traceback (most recent call last):
  File "/tmp/.mount_Dash-EpL4zwF/usr/bin/electrum-dash", line 83, in <module>
    from electrum_dash.logging import get_logger, configure_logging  # import logging submodule first
  File "/tmp/.mount_Dash-EpL4zwF/usr/lib/python3.10/site-packages/electrum_dash/__init__.py", line 16, in <module>
    from .wallet import Wallet
  File "/tmp/.mount_Dash-EpL4zwF/usr/lib/python3.10/site-packages/electrum_dash/wallet.py", line 70, in <module>
    from .storage import StorageEncryptionVersion, WalletStorage
  File "/tmp/.mount_Dash-EpL4zwF/usr/lib/python3.10/site-packages/electrum_dash/storage.py", line 39, in <module>
    from .wallet_db import WalletDB
  File "/tmp/.mount_Dash-EpL4zwF/usr/lib/python3.10/site-packages/electrum_dash/wallet_db.py", line 43, in <module>
    from .paymentrequest import PaymentRequest
  File "/tmp/.mount_Dash-EpL4zwF/usr/lib/python3.10/site-packages/electrum_dash/paymentrequest.py", line 49, in <module>
    from .network import Network
  File "/tmp/.mount_Dash-EpL4zwF/usr/lib/python3.10/site-packages/electrum_dash/network.py", line 59, in <module>
    from .dash_net import DashNet
  File "/tmp/.mount_Dash-EpL4zwF/usr/lib/python3.10/site-packages/electrum_dash/dash_net.py", line 47, in <module>
    from .dash_ps_net import PSDenoms, PRIVATESEND_QUEUE_TIMEOUT
  File "/tmp/.mount_Dash-EpL4zwF/usr/lib/python3.10/site-packages/electrum_dash/dash_ps_net.py", line 6, in <module>
    from .blspy_wrapper import BasicSchemeMPL, G1Element, G2Element
  File "/tmp/.mount_Dash-EpL4zwF/usr/lib/python3.10/site-packages/electrum_dash/blspy_wrapper.py", line 62, in <module>
    raise ImportError('Can not import blspy')
ImportError: Can not import blspy
```

A `python-blspy` package is [available](https://aur.archlinux.org/packages/python-blspy) in AUR, however it's unmaintained and does not build on my system as is.

Should I pursue installing python blspy package on my system in order to use Electrum-Dash?

**Comment by ichEben** [comment]
Same Problem with starting the AppImage on a Ubuntu 22.04 LTS Client

**Comment by eloyesp** [comment]
As far as I understand, the AppImage bundle the dependencies, so this error seems to be a missing package on the generated bundle. I'm having the same error.

**Comment by Skribinto** [comment]
Having the same error on Ubuntu 22.04 LTS.

**Comment by josephivanav** [comment]
Having the same error on Kali Linux

**Comment by dkaparis** [comment]
I confirm the current 4.1.7.5 release solved the issue for me.
